// <auto-generated />
using ControleGastos.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControleGastos.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("ControleGastos.Modelos.PessoaEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Idade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Pessoas", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pessoas_Idade", "Idade >= 0 AND Idade <= 150");
                        });
                });

            modelBuilder.Entity("ControleGastos.Modelos.TransacaoEntidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("TEXT");

                    b.Property<int>("PessoaId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Tipo")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ValorEmCentavos")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PessoaId");

                    b.ToTable("Transacoes", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transacoes_Tipo", "Tipo IN (1, 2)");

                            t.HasCheckConstraint("CK_Transacoes_Valor", "ValorEmCentavos > 0");
                        });
                });

            modelBuilder.Entity("ControleGastos.Modelos.TransacaoEntidade", b =>
                {
                    b.HasOne("ControleGastos.Modelos.PessoaEntidade", "Pessoa")
                        .WithMany("TransacaoEntidade")
                        .HasForeignKey("PessoaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pessoa");
                });

            modelBuilder.Entity("ControleGastos.Modelos.PessoaEntidade", b =>
                {
                    b.Navigation("TransacaoEntidade");
                });
#pragma warning restore 612, 618
        }
    }
}
